### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by wwwfreedbanl** [martindsouza/docker-oracle-setup#2]
Hi,
Nice summary, thanks.
Just saw a small copy/paste error in the Useful Commands-Quick Start section.
start should be replaced with stop.

# Stop
docker start -t 200 oracle
docker start -t 200 ords-504
docker start -t 200 ords-513

**Comment by martindsouza** [comment]
@wwwfreedbanl  thanks for pointing it out. Fixed the typo.
